### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by gaurav-nelson** [oasp/asciidoc-link-checker#2]
OS: Fedora 26
Node: v7.10.0
NPM: 5.0.3

Steps:
1. `npm install -g @oasp/asciidoc-link-checker`
2. `linkchecker ./test-docs-repo/`
3. Getting the error `/usr/bin/env: ‘node\r’: No such file or directory`.

**Comment by gaurav-nelson** [comment]
@salfuve any updates?

**Comment by sjimenez77** [comment]
We think that the issue is related to the encoding of the files. Let me check it, please.

**Comment by sjimenez77** [comment]
Hi @gaurav-nelson, 
Now it seems to be solved. Could you check it please?

**Comment by gaurav-nelson** [comment]
@sjimenez77 Thanks for fixing this. All good!
